version: '3'
services:
  adventure-notes-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      JWT_SECRET: supersecret
    ports:
      - 127.0.0.1:${ADVENTURE_NOTES_API_DEBUG:-9229}:9229
      - 4000:80
    volumes:
      - ./src:/usr/app/src
      - ./dist:/usr/app/dist
  adventure-notes-db:
    image: mongo:latest
    volumes:
      - adventure-notes-db:/data/db
volumes:
  adventure-notes-db: {}
