version: '3'
services:
  adventure-notes-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - adventure-notes-db
    environment:
      JWT_SECRET: supersecret
    ports:
      - 4000:80
      - 127.0.0.1:${ADVENTURE_NOTES_API_DEBUG:-9229}:9229
    volumes:
      - ./src:/usr/app/src
      - ./dist:/usr/app/dist
  adventure-notes-db:
    image: mongo:latest
    command: --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - adventure-notes-db-test:/data/db
volumes:
  adventure-notes-db-test: {}
