version: '3'
services:
  adventure-notes-api:
    build:
      context: .
    environment:
      JWT_SECRET: supersecret
    ports:
      - 4000:80
  adventure-notes-db:
    image: mongo:latest
    volumes:
      - adventure-notes-db:/data/db
volumes:
  adventure-notes-db: {}
